package questions1to6;
/**
 * 
 * @author DELL
 *No, we can't use finally without a try block
 */

public class Q3 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("hiii finally");

//		finally{
//			System.out.println("inside finally block");
//		}
	}

}
